version: "3.8"

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#
  db:
    container_name: 'thutoi_db'
    image: postgres:latest
    environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    ports:
        - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    container_name: 'thutoi_redis'
    image: redis:latest
    ports:
        - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
